# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: Blog
    url: blog/
    weight: 30
  - name: Projects
    url: showcase/
    weight: 40
  - name: About
    url: about/
    weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs â†—"
    url: "https://docs.hugoblox.com"
    weight: 3
